spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 4
      max-concurrency: 8
  pool:
    create-connection-on-startup: true
    expiry-timeout: 0
    max-connections: 1
    reconnect-on-exception: true
